Updated Documentation
georgia-tech-db/eva pull request #100
Opened 2020-09-03 21:08 UTC by Abdullahshah

I created a script `generate_documentation.py` which creates the documenation `.rst` using the jinja templating engine. 
(this script can only be run from the root directory -> but there is a check for this in the script)

To test these changes, enter the conda environment, navigate to the directory `api-docs` and run `make html`. This will generate a local copy of the website under the directory `_build` which you can open in your browser.

2020-09-08 16:15 UTC, gaurav274 requested changes
Please also add the installation dependencies to build using sphinx .

2020-09-08 20:23 UTC, gaurav274 commented on api-docs/generate_documentation.py
> +if "__pycache__" in folders:
Make a list of ignore_folders

2020-09-08 20:23 UTC, gaurav274 commented on api-docs/generate_documentation.py
> +    for (dirpath, dirnames, filenames) in walk('src/' + folder):
Move line number 64-70 to function

2020-09-08 20:23 UTC, gaurav274 commented on api-docs/generate_documentation.py
> +            fh.write(rendered_main_rst_template)
Modularize this script

2020-09-08 20:23 UTC, gaurav274 commented on api-docs/generate_documentation.py
> +    if createDocsSubFolder:
Make it generic enough to handle nested directories

2020-10-01 21:48 UTC, Abdullahshah commented on api-docs/documentation_old/catalog/catalog.models.rst
> +catalog.models package
Removed both.

2020-10-01 21:49 UTC, Abdullahshah commented
No longer need generate_documentation.py. Deprecating that script for now but may need it later if api-docs needs further changes.

2020-10-01 21:56 UTC, Abdullahshah reviewed
Check the Conversation tab for updates to documentation process.

2020-10-22 00:52 UTC, gaurav274 commented
@Abdullahshah  Any updates on this PR? Let's merge this as early as possible.

2020-10-22 21:59 UTC, xzdandy commented
Add sphinx to conda environment file.

2020-10-28 21:59 UTC, gaurav274 approved these changes
LGTM

2020-10-28 22:00 UTC, merged