Lliu374
georgia-tech-db/eva pull request #140
Opened 2021-02-13 03:12 UTC by llxxll12345

Finished writing "EXPLODE" operator. With Unnest planner and executor added. Tests yet to be added.

2021-02-13 04:11 UTC, xzdandy commented
Do not add eva_dataset into the repo.

2021-02-13 05:07 UTC, gaurav274 requested changes
1. Remove the binary files.
2. Replace explode with unnest.

I'll add more comments for other edits.

2021-02-13 20:26 UTC, llxxll12345 commented on src/parser/evaql/evaql_lexer.g4
> +EXPLODE:                             'EXPLODE';
choose to stick with explode now.

2021-02-14 03:48 UTC, jiashenC commented
I think even though the file is deleted, it will still be stored in the git history tree [some references](https://www.deployhq.com/git/faqs/removing-large-files-from-git-history), which slows down other commits. Probably we need to filter out those histories.

2021-02-14 05:49 UTC, xzdandy commented
> I think even though the file is deleted, it will still be stored in the git history tree [some references](https://www.deployhq.com/git/faqs/removing-large-files-from-git-history), which slows down other commits. Probably we need to filter out those histories.

That's a good point. @llxxll12345 Check if you are able to filter out those histories.

2021-02-15 03:39 UTC, closed without merging