Packaging
georgia-tech-db/eva pull request #193
Opened 2021-11-15 16:51 UTC by suryatejreddy

2021-12-10 01:33 UTC, gaurav274 commented on setup.cfg
> +author_email = svyalla3@gatech.edu
Use the DB email id Joy shared

2021-12-13 02:08 UTC, gaurav274 requested changes

2021-12-13 02:08 UTC, gaurav274 commented on test/eva_cmd_client.py
> +    def dummyTest(self):
rename it to start with **test_**

2021-12-13 02:08 UTC, gaurav274 commented on test/eva_server.py
> +    def dummyTest(self):
rename to start with **test_**

2021-12-18 09:37 UTC, xzdandy commented
A dump question: how shall I test this packaging on a clean machine? Do we still need the installation scripts (script/install) and mysql configuration first?

2021-12-18 16:35 UTC, suryatejreddy commented
> A dump question: how shall I test this packaging on a clean machine? Do we still need the installation scripts (script/install) and mysql configuration first?



> A dump question: how shall I test this packaging on a clean machine? Do we still need the installation scripts (script/install) and mysql configuration first?

@xzdandy You can install it using this sample pypi package https://pypi.org/project/evatestdb/. 

use `eva_server` and `eva_client` to start the server and client. Let me know if it doesn't work on your machine.

2021-12-19 01:19 UTC, xzdandy commented
> @xzdandy You can install it using this sample pypi package https://pypi.org/project/evatestdb/.
> 
> use `eva_server` and `eva_client` to start the server and client. Let me know if it doesn't work on your machine.

@suryatejreddy Thanks, I will try it. PS: Is `pip install evatestdb` same as `python setup.py install` in this pr (branch suryatejreddy:packaging)?

2022-03-25 05:20 UTC, closed without merging

2022-03-25 05:20 UTC, gaurav274 commented
Duplicate