Lateral Join (and Hash Join)
georgia-tech-db/eva pull request #236
Opened 2022-04-03 21:19 UTC by suryatejreddy

The following type of queries are supported:
- `SELECT id FROM MyVideo, 
LATERAL Unnest(FastRCNNObjectDetector(data))`
- SELECT id FROM MyVideo, 
LATERAL Unnest(FastRCNNObjectDetector(data)) 
WHERE labels = 'car';
- SELECT id, labels FROM MyVideo,
LATERAL Unnest(FastRCNNObjectDetector(data)) 
WHERE labels = 'car' and Color(data, boxes) = 'BLUE';

The PR also adds support for Hash Join on two structured tables based on common columns.

2022-04-04 23:16 UTC, gaurav274 requested changes

2022-04-04 23:16 UTC, gaurav274 commented on eva/parser/parser_visitor/_table_sources.py
> +                join_type = JoinType.HASH_JOIN
Join can be one of these https://www.techonthenet.com/postgresql/joins.php. Don't call hash a separate type.

2022-04-05 04:09 UTC, gaurav274 requested changes

2022-04-06 20:02 UTC, xzdandy requested changes
Need integration test.

2022-06-05 19:13 UTC, closed without merging