feat: saliency maps
georgia-tech-db/eva pull request #803
Opened 2023-06-01 18:13 UTC by vivek-mandal

Added Generalised model
Updated the notebook link with new EVA API

2023-06-01 22:40 UTC, jarulraj commented
Is it possible to visualize the features on the image in the notebook? remove the old API notebook

2023-06-02 03:59 UTC, affan00733 requested changes

2023-06-02 03:59 UTC, affan00733 commented on eva/udfs/saliency_feature_extractor.py
> +from PIL import Image
make sure you had successfully executed `bash script/test/test.sh -m "LINTER"   `

2023-06-02 21:14 UTC, jarulraj commented
Running this test on a server with GPU:

`pytest -k 'test_saliency' -s -v  `

```eva.executor.executor_utils.ExecutorError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor```

2023-06-02 21:15 UTC, jarulraj commented
@vivek-mandal Look at my changes in -- https://github.com/georgia-tech-db/eva/tree/vivek-mandal-SaliencyMaps_Updated

2023-06-05 14:46 UTC, merged